### ISSUE TITLE
Dataset: Credit Card customers

### ISSUE THREAD

**Issue by kozaka93** [mini-pw/2021L-WB-XAI-1#1]
_Problem:_ Klienci banku rezygnują z usług związanych z kartami kredytowymi. Chcemy zbadać, którzy klienci mogą być chętni do odejścia od tej usługi (customer churn).

_Dane:_ Dane Credit Card dostępne są na kaggle: https://www.kaggle.com/sakshigoyal7/credit-card-customers 
Zbiór danych zawiera 10 tyś. obserwacji, 18 zmiennych objaśniających.

W celu przygotowania modeli związanych z predykcją przepływu klinetów należy odtworzyć notebook: https://www.kaggle.com/alpertml/credit-card-customers-eda-ml-97-5-accuracy

W ramach projektu można również wytrenować swoje modele do porównania.

**Comment by PrzeChoj** [comment]
komentarz

**Comment by kozaka93** [comment]
- [ ] EDA (18.03.2021)
- [ ] Modele (25.03.2021)
- [ ] Literatura w postaci BibTeX (15.04.2021)
- [ ] Wyjaśnienia lokalne (25.04.2021)
- [ ] Wyjaśnienia globalne (16.05.20121)
- [ ] Wstępne dodanie raportu - dla chętnych (23.05.2021)
