### ISSUE TITLE
Dataset: California Housing Prices

### ISSUE THREAD

**Issue by kozaka93** [mini-pw/2021L-WB-XAI-1#2]
_Problem:_ Zbiór danych opisuje nieruchomości w stanie Kalifornia. Chcemy modelować medianę wartości domu dla gospodarstw domowych w obrębie bloku (mierzona w dolarach amerykańskich).

_Dane:_ Dane zawierają informacje z kalifornijskiego spisu powszechnego z 1990 roku, dostępne są na kaggle: https://www.kaggle.com/camnugent/california-housing-prices
Zbiór danych zawiera 20640 obserwacji, 10 zmiennych objaśniających.

W celu przygotowania modeli związanych z predykcją mediany wartości domu należy odtworzyć: https://www.kaggle.com/ravichaubey1506/end-to-end-machine-learning, 
https://www.kaggle.com/takedown/complete-tutorial-for-beginners 

W ramach projektu można również wytrenować swoje modele do porównania.

**Comment by deregowskis** [comment]
Sebastian, Maciek, Paweł

**Comment by kozaka93** [comment]
- [ ] EDA (18.03.2021)
- [ ] Modele (25.03.2021)
- [ ] Literatura w postaci BibTeX (15.04.2021)
- [ ] Wyjaśnienia lokalne (25.04.2021)
- [ ] Wyjaśnienia globalne (16.05.20121)
- [ ] Wstępne dodanie raportu - dla chętnych (23.05.2021)
