### ISSUE TITLE
Dataset: Heart Disease UCI

### ISSUE THREAD

**Issue by kozaka93** [mini-pw/2021L-WB-XAI-1#3]
_Problem:_ Zbiór danych opisuje pacjentów (mających lub nie chorobę serca). Chcemy wykorzystać te dane do stworzenia modelu, który spróbuje przewidzieć, czy pacjent ma tę chorobę, czy nie.

_Dane:_ Dane Heart Disease UCI dostępne są na kaggle: https://www.kaggle.com/ronitf/heart-disease-uci 
Zbiór danych zawiera 303 obserwacji, 14 zmiennych objaśniających.

W celu przygotowania modeli związanych z predykcją choroby serca należy odtworzyć notebook:https://www.kaggle.com/cdabakoglu/heart-disease-classifications-machine-learning 

W ramach projektu można również wytrenować swoje modele do porównania.

**Comment by rrolkiewicz** [comment]
Renata Rólkiewicz, Paulina Przybyłek, Patryk Słowakiewicz

**Comment by kozaka93** [comment]
- [ ] EDA (18.03.2021)
- [ ] Modele (25.03.2021)
- [ ] Literatura w postaci BibTeX (15.04.2021)
- [ ] Wyjaśnienia lokalne (25.04.2021)
- [ ] Wyjaśnienia globalne (16.05.20121)
- [ ] Wstępne dodanie raportu - dla chętnych (23.05.2021)
