### ISSUE TITLE
Dataset: Red Wine Quality

### ISSUE THREAD

**Issue by kozaka93** [mini-pw/2021L-WB-XAI-1#4]
_Problem:_ Chcemy określić jakość wina na podstawie zmiennych fizykochemicznych. W danych mamy kilka klas (multiclass), ale dzielmy jest na dwie podgrupy uzyskując klasyfikację binarną.

_Dane:_ Dane Red Wine Quality dostępne są na kaggle: https://www.kaggle.com/uciml/red-wine-quality-cortez-et-al-2009 
Zbiór danych zawiera 1599 obserwacji, 12 zmiennych objaśniających.

W celu przygotowania modeli związanych z predykcją jakości wina należy odtworzyć notebook: https://www.kaggle.com/vishalyo990/prediction-of-quality-of-wine

W ramach projektu można również wytrenować swoje modele do porównania.

**Comment by Kostee** [comment]
CZERWONI
1. Jakub Kosterna
2. Bartosz Siński
3. Jan Smoleń

**Comment by kozaka93** [comment]
- [ ] EDA (18.03.2021)
- [ ] Modele (25.03.2021)
- [ ] Literatura w postaci BibTeX (15.04.2021)
- [ ] Wyjaśnienia lokalne (25.04.2021)
- [ ] Wyjaśnienia globalne (16.05.20121)
- [ ] Wstępne dodanie raportu - dla chętnych (23.05.2021)
