### ISSUE TITLE
Dataset: Hotel booking demand

### ISSUE THREAD

**Issue by kozaka93** [mini-pw/2021L-WB-XAI-1#6]
_Problem:_ Zarządzając hotelem chcemy dobrze planować zapotrzebowanie na personel oraz na żywność. Chcemy zbudować model przewidujący czy gość rzeczywiście skorzysta z zarezerwowanego pokoju.

_Dane:_ Dane Hotel booking demand dostępne są na kaggle: 
https://www.kaggle.com/jessemostipak/hotel-booking-demand 
Zbiór danych zawiera 119 tyś. obserwacji, 32 zmiennych objaśniających.

W celu przygotowania modeli związanych z predykcją odwołań rezerwacji należy odtworzyć notebook: https://www.kaggle.com/marcuswingen/eda-of-bookings-and-ml-to-predict-cancelations 

W ramach projektu można również wytrenować swoje modele do porównania.

**Comment by krzyzinskim** [comment]
Ania, Artur, Mateusz

**Comment by kozaka93** [comment]
- [ ] EDA (18.03.2021)
- [ ] Modele (25.03.2021)
- [ ] Literatura w postaci BibTeX (15.04.2021)
- [ ] Wyjaśnienia lokalne (25.04.2021)
- [ ] Wyjaśnienia globalne (16.05.20121)
- [ ] Wstępne dodanie raportu - dla chętnych (23.05.2021)
